### ISSUE TITLE
image-rs dramatically increases filesize of animated gifs that are loaded in and re-encoded

### ISSUE THREAD

**Issue by sam0x17** [image-rs/image#1728]
This happens when encoding animated gifs. Some animated gifs become significantly larger (more than 50%) when they get loaded into image-rs, and then re-encoded and saved without making any other changes.

## Expected

When loading an animated gif into image-rs and re-saving it, you should get roughly the same filesize or smaller.

## Actual behaviour

Often times I end up with a much larger filesize (sometimes even 2x or 5x). My guess is there is no optimization of color palates going on or something like that resulting in poor compression. Just a guess.

## Reproduction steps

This image starts at 641261 bytes and comes out as 2613166 bytes (400% increase in size). 

![large_animated](https://user-images.githubusercontent.com/1855021/173870668-a5f311a4-cd3a-4889-a729-659df7fef875.gif)

code:
```rust
fn main() {
    let f = File::open("large_animated.gif").unwrap();
    let decoder = GifDecoder::new(f).unwrap();
    let dest_w: u32 = 352; // hard coding width and height to that of the
    let dest_h: u32 = 240; // input image for demonstration purposes
    if let Ok(frames) = decoder.into_frames().collect_frames() {
        let mut resized_frames = Vec::new();
        for frame in &frames {
            let resized =
                imageops::resize(&frame.buffer().clone(), dest_w, dest_h, FilterType::CatmullRom);
            resized_frames.push(Frame::new(resized));
        }
        let gif_out = File::create("out.gif").unwrap();
        let mut encoder = GifEncoder::new(gif_out);
        encoder.set_repeat(image::gif::Repeat::Infinite).unwrap();
        encoder.encode_frames(resized_frames.into_iter()).unwrap();
    }
}
```

## Impact

This is causing problems because we are using image-rs to process animated gifs in our platform's user-facing file uploader (for a service used by hundreds of thousands of users). Because we send images over SMS, there is a strict filesize limit and users are providing gifs that meet the requirements but then because image-rs increases the size significantly, these often fail to send.

**Comment by sam0x17** [comment]
Note that we are resizing to the same size here just as a toy example. In reality we are usually downsizing a bit. Resizing to the same size should be a no-op.

**Comment by HeroicKatora** [comment]
I'm unsure how to turn this report into something actionable. Everything here is working as documented, decoding into a pixel matrix does not preserve format specific metadata.

- Are you searching for guidance, in order to contribute engineering work effectively, given that you provided an affected business case you might even have a budget for such work?
- Do you have a concrete idea for improving this roundtrip, if so, feel free to provide a sketch of implementation?
- Are you unsure whether you missed a known workaround or better code structure to avoid the problem?

**Comment by sam0x17** [comment]
Totally understand, let me clarify. The problem isn't that metadata isn't being preserved, it's that the compression image-rs is producing for animated gifs is dramatically worse than the compression exhibited by input images, across the board. I don't think this is a metadata thing, image-rs is clearly doing sometihng wrong or sub-optimal with how it is encoding animated gifs that results in a dramatically larger filesize. I thought that would be something you guys would like to fix?

If not, I'm happy to investigate this myself. My theory is it's something with color palates, but would appreciate any theories or guidance

**Comment by HeroicKatora** [comment]
* The palette isn't the only metadata. If the input does DisposalMethod::Keep frames then we expand each of the frames to a full image but re-encoding doesn't try to find smaller delta encoded frames. Use gif optimizers to reduce file size in this case, or use `gif` directly for encoding with detection of appropriate regions. I'm not aware of a Rust library for detecting those regions, if you happen to modify code to recalculate it (see point on blending below) then please ping and we can figure out how to add it to the encoding process in `image`.

* The palette is also metadata, and at encoding they are being re-calculated from scratch. Slightly confusing: when encoding the exact image (which has < 256 colors) then I had the impression that we chose those as the palette so the only difference might be the order of color. That *does* have an influence on size due but should be small due to lzw coding. Maybe we should improve test coverage to known more specifically.

* However, when you resize *with interpolation* then surely a lot of newly blended colors are created. Then the imagequant kicks in to create a completely new palette.

**Comment by HeroicKatora** [comment]
Hm, might it be encoding the palette for *each* frame instead of utilizing a single global palette as in the original image?

<details>
<summary>Before</summary>

```
 Frame:
  delay: 8
  canvas: 352x240+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 351x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x225+0+14
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x230+0+9
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 351x239+1+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x235+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 350x239+2+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 320x235+32+1
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 304x214+0+7
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 351x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 339x226+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 338x235+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x236+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 350x239+2+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 10
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 351x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x236+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 326x239+15+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 343x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 349x232+3+7
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 333x239+8+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 347x239+5+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 338x239+14+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 329x239+23+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x224+0+15
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 350x239+2+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 347x239+5+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 347x236+5+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 334x239+18+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 342x239+3+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x237+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 351x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 330x239+8+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 352x239+0+0
  dispose: Keep
  needs_input: false
  palette: false
 Frame:
  delay: 8
  canvas: 348x239+4+0
  dispose: Keep
  needs_input: false
  palette: false
```

</details>

<details>
<summary>After</summary>

```
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
 Frame:
  delay: 0
  canvas: 352x240+0+0
  dispose: Background
  needs_input: false
  palette: true
```

</details>

That could be addressed much more directly.
