### ISSUE TITLE
Rgb32FImage fails to save as PNG

### ISSUE THREAD

**Issue by AugLuk** [image-rs/image#1999]
image-rs version 0.24.7 (latest)
Rust versions 1.69.0 and 1.72.0 (latest) targeting 'stable-aarch64-apple-darwin' on an M2 Mac.

## Expected

Image is saved properly.

## Actual behaviour

Thread "main" panics and an empty file is saved.

## Reproduction steps

`Cargo.toml`:
```toml
[package]
name = "noise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
```

`src/main.rs`:
```rust
fn main() {
    image::Rgb32FImage::new(256, 256).save("img.png").unwrap();
}
```

Running `RUST_BACKTRACE=1 cargo run` produces:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/noise`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Encoding(EncodingError { format: Exact(Png), underlying: Some(ColorType(Rgb32F)) })', src/main.rs:2:55
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: noise::main
             at ./src/main.rs:2:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Notes
Rgb32F OpenEXR saves without issues, leading me to suspect the problem happens while encoding PNG.
