### ISSUE TITLE
 Insufficient memory error when using image::load_from_memory while image is only 2mb

### ISSUE THREAD

**Issue by MrSn0wy** [image-rs/image#2092]
Heya, i'm trying to download a image and make it in the avif format, this works with most images i have tested however i had this one image where i kept getting the  `Insufficient memory` error. i have checked the size of the image and its only 2mb so i really don't understand the problem since i have enough memory, if anyone can help me out that would be really appreciated, also sorry if the code doesn't make the most sense, i'm still learning rust but i tried my best haha

```rust
// here is a different url you can try that does work: https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA24899_00/1/i_9d292798534ec68c44fdaed2d5822cae587aecd40087095f7b6ee446fac1f2cf/i/icon0.png

fn main() {
    let url = "https://gs2-sec.ww.prod.dl.playstation.net/gs2-sec/appkgo/prod/CUSA02343_00/1/i_83c8ab228dea4223dc1005e0d7b37f7e5553057fc3e5d11e0fccf4daef402bc3/i/icon0.png";

    match image_downloader(url, "./image.avif") {
        Ok(_) => {
            println!("Image downloaded successfully!");
        }
        Err(err) => {
            println!("Error downloading image! {}", err);
        }
    }
}

fn image_downloader(url: &str, location: &str) -> Result<(), anyhow::Error> {
    // Download the image
    let response = ureq::get(&url).call()?;
    let mut reader = response.into_reader();

    // put it into a buffer
    let mut buffer = Vec::new();
    reader.read_to_end(&mut buffer)?;

    // load the image from the buffer (here happens the error)
    let img = image::load_from_memory(&buffer)?;
    // let img = image::load_from_memory_with_format(&buffer, image::ImageFormat::Png)?; // gives the same error

    // resize the image
    let resized_img = img.resize_exact(256, 256, image::imageops::Lanczos3);

    // save the image as avif
    resized_img.save_with_format(location, image::ImageFormat::Avif)?;
    Ok(())
}
```

```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
ureq = "2.9.1"
image = { version = "0.24.7", features = ["avif-encoder", "jpeg", "png"]}
```
