### ISSUE TITLE
Error: The encoder or decoder for Jpeg does not support the color type `Rgba8`

### ISSUE THREAD

**Issue by voratham** [image-rs/image#2211]
I want to use the DynamicImage.thumbnail method but I got the error ```Error: The encoder or decoder for Jpeg does not support the color type Rgba8".```

Here is an example of the code below: 
```rs
use image::io::Reader as ImageReader;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let img_original = ImageReader::open("02.png")?.decode()?;

    img_original.thumbnail(100, 100);
    img_original.save("02.jpg")?;

    Ok(())
}

```

My Cargo.toml
```toml
[package]
name = "demo_image_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
image = "0.25.1"
tokio = { version = "1.37.0", features = ["full"] }

```
