### ISSUE TITLE
WEBP decoded as grayscale

### ISSUE THREAD

**Issue by fenhl** [image-rs/image#912]
When [my Discord avatar](https://cdn.discordapp.com/avatars/86841168427495424/31e6a3d39336e5c9333f8af8c8801d55.webp?size=1024) is loaded using this library, it becomes grayscale. Minimal test case:

# Cargo.toml

```toml
[package]
name = "image-test"
version = "0.1.0"
edition = "2018"

[dependencies]
image = "=0.21.1"
reqwest = "=0.9.15"
```

# main.rs

```rust
use std::io::{
    Cursor,
    prelude::*
};
use image::ImageFormat;

fn main() {
    let mut buf = Vec::default();
    reqwest::get("https://cdn.discordapp.com/avatars/86841168427495424/31e6a3d39336e5c9333f8af8c8801d55.webp?size=1024")
        .unwrap()
        .read_to_end(&mut buf)
        .unwrap();
    image::load(Cursor::new(buf), ImageFormat::WEBP).unwrap().save("test.png").unwrap();
}
```

# Output

After running the test case, the file `test.png` in the crate root is a grayscale version of my avatar.
